name: Listeyi Guncelle

on:
  schedule:
    - cron: '0 */3 * * *' # 3 saatte bir
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Depoyu Çek
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Requests Kur
        run: pip install requests

      - name: Scripti Başlat
        run: python main.py 
        # Python dosyanın adı main.py olsun!

      - name: GitHub'a Yükle
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@github.com"
          git add yeni.m3u
          git commit -m "Guncelleme: $(date)" || echo "Degisiklik yok"
          git push
