name: Canli TV Guncelleyici

on:
  schedule:
    - cron: '0 */3 * * *' # 3 Saatte bir
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Depoyu Cek
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Request Kutuphanesini Kur
        run: pip install requests

      - name: Scripti Calistir
        # BURAYA DİKKAT: Python dosyanın adı neyse onu yaz!
        run: python gbl.py 

      - name: Commit ve Push Islemi
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          if [ -f yeni.m3u ]; then
            git add yeni.m3u
            git commit -m "Liste guncellendi" || exit 0
            git push
          else
            echo "Dosya olusmadi, yukleme yapilamadi."
          fi
