name: Canli TV M3U Güncelleyici

on:
  schedule:
    - cron: '0 */3 * * *' # 3 saatte bir
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-tv:
    runs-on: ubuntu-latest
    
    steps:
      - name: Depoyu Çek
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gereksinimleri Yükle
        run: pip install requests

      - name: Scripti Çalıştır
        # Python dosyanın adı neyse onu yaz (gbl.py veya main.py)
        run: python gbl.py 

      - name: GitHub'a Yükle
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@github.com"
          
          if [ -f "yeni.m3u" ]; then
            git add yeni.m3u
            git commit -m "TV Listesi Güncellendi: $(date)" || echo "Değişiklik yok."
            git push
          else
            echo "Dosya oluşmadı, yükleme yapılmıyor."
          fi
