name: Listeyi Guncelle

on:
  schedule:
    - cron: '0 */4 * * *' # Her 4 saatte bir çalıştır
  workflow_dispatch: # Elle tetiklemek için buton

permissions:
  contents: write # Dosyayı kaydetme izni ver

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Python Kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: yt-dlp Yukle
      run: pip install -r requirements.txt

    - name: Botu Calistir
      run: python bot.py

    - name: Degisiklikleri Kaydet
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add YouTube.m3u
        # Eğer değişiklik varsa commit at, yoksa hata verme
        git commit -m "Otomatik Guncelleme" || exit 0
        git push
        
